# Local development setup for Microtales
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=micro-tales-app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/micro-tales-app
      - AUTH_SECRET=your_auth_secret_here
      - NODE_ENV=development
    command: sh -c "pnpm db:generate && pnpm db:migrate && pnpm db:seed && node server.js"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: